import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Shield, ChevronLeft, Heart, CheckCircle, AlertTriangle } from 'lucide-react';
import Navbar from './Navbar';

export default function Terms() {
  const navigate = useNavigate();

  return (
    <div className="bg-immersive min-h-screen pb-24">
      <Navbar />
      
      <main className="floating-container animate-slide-up">
        <div className="main-floating-card p-12 mt-4">
          <div className="mb-12 flex items-center justify-between">
            <div>
              <h1 className="text-[42px] font-black tracking-tighter leading-tight">Terms of Operation</h1>
              <p className="text-[14px] font-bold text-gray-400 uppercase tracking-widest mt-2">Protocol Compliance & Authorization</p>
            </div>
            <button
              onClick={() => navigate(-1)}
              className="flex items-center gap-2 text-[12px] font-black uppercase text-[#008cff] hover:underline"
            >
              <ChevronLeft size={16} /> Return to Previous Node
            </button>
          </div>

          <div className="space-y-12">
            <section className="bg-gray-50 p-8 rounded-[12px] border border-gray-100">
              <div className="flex items-center gap-4 mb-6">
                <div className="w-1.5 h-8 bg-[#008cff] rounded-full" />
                <h2 className="text-[20px] font-black uppercase italic">1. Initial Protocol</h2>
              </div>
              <p className="text-[16px] text-gray-600 font-medium leading-relaxed italic">
                Welcome to MediScan. These operational protocols govern your access to our neural diagnostic core, clinical archives, and specialist network. By initializing a session, you agree to these clinical parameters.
              </p>
            </section>

            <section>
              <div className="flex items-center gap-4 mb-8">
                <div className="w-1.5 h-8 bg-[#008cff] rounded-full" />
                <h2 className="text-[20px] font-black uppercase italic">2. Node Responsibilities</h2>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {[
                  'Provide accurate biometric information',
                  'Maintain neural key confidentiality',
                  'Authorized clinical use only',
                  'No third-party node sharing',
                  'Compliance with global bio-laws',
                  'No platform reverse-engineering'
                ].map((item, i) => (
                  <div key={i} className="section-card border rounded-[12px] flex items-center gap-4 group">
                    <CheckCircle size={20} className="text-[#008cff]" />
                    <span className="text-[13px] font-bold text-gray-700 uppercase tracking-tight">{item}</span>
                  </div>
                ))}
              </div>
            </section>

            <section className="p-10 bg-red-50 border border-red-100 rounded-[12px]">
              <div className="flex items-center gap-4 mb-6">
                <AlertTriangle size={32} className="text-red-500" />
                <h2 className="text-[20px] font-black uppercase italic text-red-700">3. Tactical Warning</h2>
              </div>
              <p className="text-[14px] font-black uppercase text-red-900/60 leading-relaxed tracking-tight">
                MEDISCAN PROVIDES ADVISORY DIAGNOSTIC DATA. INFORMATION GENERATED BY THE NEURAL CORE IS NOT A SUBSTITUTE FOR SPECIALIST INTERVENTION. ALWAYS VALIDATE DATA WITH A BIOLOGICAL SPECIALIST.
              </p>
            </section>

            <section className="bg-gray-50 p-8 rounded-[12px] border border-gray-100">
              <div className="flex items-center gap-4 mb-6">
                <div className="w-1.5 h-8 bg-[#008cff] rounded-full" />
                <h2 className="text-[20px] font-black uppercase italic">4. Identity Verification</h2>
              </div>
              <p className="text-[16px] text-gray-600 font-medium leading-relaxed italic">
                To prevent the creation of fraudulent or duplicate identities, all nodes must undergo mandatory identity verification during enrollment. This process requires the submission of a valid, government-issued biometric identifier (such as an Aadhaar number or equivalent national ID). By submitting this information, you authorize MediScan to validate your identity for the sole purpose of ensuring platform integrity and securing the neural network against fake accounts.
              </p>
            </section>
          </div>

          <div className="mt-16 flex flex-col md:flex-row gap-6">
            <button
              onClick={() => navigate('/signup')}
              className="flex-1 btn-search !text-[16px] py-4"
            >
              AUTHORIZE COMPLIANCE
            </button>
            <button
              onClick={() => navigate(-1)}
              className="flex-1 py-4 border-2 border-gray-200 rounded-full text-[14px] font-black uppercase tracking-widest hover:bg-gray-100 transition-all"
            >
              REJECT PROTOCOL
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}
