import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Shield, ChevronLeft, ChevronRight, CheckCircle, AlertTriangle, FileText, Lock, Fingerprint, Activity, ShieldCheck } from 'lucide-react';
import Navbar from './Navbar';

export default function Terms() {
  const navigate = useNavigate();
  const [agreed, setAgreed] = useState(false);

  const sections = [
    {
      id: 1,
      icon: Activity,
      title: "Initial Protocol",
      desc: "Welcome to MediScan. These operational protocols govern your access to our neural diagnostic core, clinical archives, and specialist network. By initializing a session, you agree to these clinical parameters.",
      color: "text-blue-500",
      bg: "bg-blue-500",
      lightBg: "bg-blue-50",
      borderColor: "border-blue-100"
    },
    {
      id: 2,
      icon: Lock,
      title: "Node Responsibilities",
      desc: "Maintain strict security of your credentials and operate within clinical guidelines. Failure to comply will result in immediate network ejection.",
      list: [
        'Provide accurate biometric information',
        'Maintain neural key confidentiality',
        'Authorized clinical use only',
        'No third-party node sharing',
        'Compliance with global bio-laws',
        'No platform reverse-engineering'
      ],
      color: "text-indigo-500",
      bg: "bg-indigo-500",
      lightBg: "bg-indigo-50",
      borderColor: "border-indigo-100"
    },
    {
      id: 3,
      icon: AlertTriangle,
      title: "Tactical Warning",
      desc: "MEDISCAN PROVIDES ADVISORY DIAGNOSTIC DATA. INFORMATION GENERATED BY THE NEURAL CORE IS NOT A SUBSTITUTE FOR SPECIALIST INTERVENTION. ALWAYS VALIDATE DATA WITH A BIOLOGICAL SPECIALIST.",
      color: "text-rose-500",
      bg: "bg-rose-500",
      lightBg: "bg-rose-50",
      borderColor: "border-rose-100",
      isWarning: true
    },
    {
      id: 4,
      icon: Fingerprint,
      title: "Identity Verification",
      desc: "To prevent the creation of fraudulent or duplicate identities, all nodes must undergo mandatory identity verification during enrollment. This process requires the submission of a valid, government-issued biometric identifier. By submitting this information, you authorize MediScan to validate your identity for the sole purpose of ensuring platform integrity and securing the neural network against fake accounts.",
      color: "text-emerald-500",
      bg: "bg-emerald-500",
      lightBg: "bg-emerald-50",
      borderColor: "border-emerald-100"
    }
  ];

  return (
    <div className="bg-immersive min-h-screen pb-24">
      <Navbar />
      
      <main className="floating-container animate-slide-up">
        <div className="max-w-[800px] mx-auto">
          {/* Header */}
          <div className="flex items-center justify-between mb-8 text-white">
            <button
              onClick={() => navigate(-1)}
              className="flex items-center gap-2 text-[12px] font-black uppercase text-blue-400 hover:text-blue-300 transition-colors bg-white/10 px-4 py-2 rounded-full backdrop-blur-md border border-white/10"
            >
              <ChevronLeft size={16} /> Return
            </button>
            <div className="flex items-center gap-2 px-4 py-2 bg-white/10 backdrop-blur-md rounded-full border border-white/10">
              <Shield size={16} className="text-blue-400" />
              <span className="text-[12px] font-bold tracking-widest uppercase text-white/80">Secure Connection</span>
            </div>
          </div>

          <div className="bg-white/95 backdrop-blur-xl rounded-[24px] shadow-2xl overflow-hidden border border-white/20">
            {/* Title Section */}
            <div className="p-8 md:p-10 border-b border-gray-100 bg-gradient-to-b from-gray-50 to-white relative overflow-hidden">
              <div className="absolute top-0 right-0 w-64 h-64 bg-blue-500/5 rounded-full blur-3xl -mr-20 -mt-20 pointer-events-none"></div>
              
              <div className="flex flex-col md:flex-row items-center gap-6 relative z-10 text-center md:text-left">
                <div className="w-20 h-20 bg-white rounded-2xl shadow-lg border border-gray-100 flex items-center justify-center shrink-0">
                  <FileText size={40} className="text-[#008cff]" />
                </div>
                <div>
                  <h1 className="text-[32px] md:text-[42px] font-black tracking-tighter leading-tight text-gray-900">Terms of Operation</h1>
                  <p className="text-[12px] md:text-[14px] font-bold text-[#008cff] uppercase tracking-widest mt-1">Protocol Compliance & Authorization</p>
                </div>
              </div>
            </div>

            {/* Content Section */}
            <div className="p-6 md:p-10 space-y-6 md:space-y-8">
              {sections.map((sec) => (
                <div 
                  key={sec.id}
                  className={`p-6 md:p-8 rounded-[20px] border transition-all duration-300 hover:shadow-lg group ${
                    sec.isWarning ? 'bg-rose-50 border-rose-100' : 'bg-white border-gray-100 hover:border-gray-300'
                  }`}
                >
                  <div className="flex flex-col md:flex-row items-start gap-5">
                    <div className={`w-12 h-12 rounded-2xl flex items-center justify-center shrink-0 transition-transform group-hover:scale-110 ${sec.lightBg}`}>
                      <sec.icon size={24} className={sec.color} />
                    </div>
                    <div>
                      <div className="flex items-center gap-3 mb-2">
                        <span className={`text-[10px] md:text-[11px] font-black uppercase tracking-widest ${sec.color} px-2 py-1 rounded-md ${sec.lightBg}`}>
                          Section 0{sec.id}
                        </span>
                        <h3 className={`text-[18px] md:text-[20px] font-black uppercase tracking-tight ${sec.isWarning ? 'text-rose-700' : 'text-gray-900'}`}>
                          {sec.title}
                        </h3>
                      </div>
                      
                      <p className={`text-[14px] md:text-[15px] font-medium leading-relaxed ${sec.isWarning ? 'text-rose-600 uppercase tracking-tight font-bold' : 'text-gray-600'}`}>
                        {sec.desc}
                      </p>

                      {sec.list && (
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-6">
                          {sec.list.map((item, i) => (
                            <div key={i} className="flex items-center gap-3 bg-gray-50 px-4 py-3 rounded-xl border border-gray-100 group-hover:bg-white transition-colors">
                              <CheckCircle size={16} className={sec.color} />
                              <span className="text-[12px] md:text-[13px] font-bold text-gray-700">{item}</span>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {/* Action Section */}
            <div className="p-6 md:p-10 bg-gray-50 border-t border-gray-100">
              <label className="flex items-start gap-4 p-5 rounded-2xl border-2 border-gray-200 hover:border-[#008cff]/50 cursor-pointer transition-all bg-white mb-8 group shadow-sm">
                <div className="relative flex items-center justify-center mt-1 shrink-0">
                  <input 
                    type="checkbox" 
                    checked={agreed}
                    onChange={(e) => setAgreed(e.target.checked)}
                    className="w-7 h-7 appearance-none border-2 border-gray-300 rounded-lg checked:bg-[#008cff] checked:border-[#008cff] transition-colors cursor-pointer peer focus:ring-4 focus:ring-blue-500/20"
                  />
                  <ShieldCheck size={16} className="text-white absolute opacity-0 peer-checked:opacity-100 pointer-events-none transition-opacity" />
                </div>
                <div>
                  <h4 className="text-[14px] md:text-[16px] font-black text-gray-900 uppercase tracking-tight group-hover:text-[#008cff] transition-colors">I acknowledge and accept the protocol</h4>
                  <p className="text-[12px] md:text-[14px] text-gray-500 mt-1 font-medium">By checking this box, you digitally sign the MediScan terms of operation and verify your compliance.</p>
                </div>
              </label>

              <div className="flex flex-col sm:flex-row gap-4">
                <button
                  onClick={() => navigate('/signup')}
                  disabled={!agreed}
                  className={`flex-1 py-4 md:py-5 rounded-2xl text-[14px] md:text-[16px] font-black uppercase tracking-widest transition-all duration-300 flex items-center justify-center gap-3 ${
                    agreed 
                      ? 'bg-gradient-to-r from-[#008cff] to-[#0056cc] text-white hover:shadow-xl hover:shadow-blue-500/30 hover:-translate-y-1' 
                      : 'bg-gray-200 text-gray-400 cursor-not-allowed'
                  }`}
                >
                  AUTHORIZE COMPLIANCE <ChevronRight size={20} className={agreed ? "animate-pulse" : ""} />
                </button>
                <button
                  onClick={() => navigate(-1)}
                  className="px-6 md:px-8 py-4 md:py-5 rounded-2xl text-[13px] md:text-[14px] font-black uppercase tracking-widest border-2 border-gray-200 text-gray-600 hover:bg-gray-200 hover:text-gray-900 transition-colors"
                >
                  REJECT
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
